[package]
name = "starclad_contracts"
version = "1.0.0"
edition = "2023_11"

[dependencies]
starknet = ">=2.5.0"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
build = "scarb build"
test = "scarb test"
format = "scarb fmt"
